HOSS2-340 | increase listed countries for autocomplete
hmrc/home-office-immigration-status-frontend pull request #112
Opened 2021-12-10 12:07 UTC by liampan

Now uses complete list set by ISO3166, swapping the name for the hmrc preferrred if one is available otherwise using the ISO default

2021-12-10 12:33 UTC, AdamCoops approved these changes

2021-12-10 12:46 UTC, burns238 requested changes
We also need to remove the RawCountries class and potentially rework the use of the pre-existing country object in the views package.

But this is a good solution, nice one

2021-12-10 12:46 UTC, burns238 commented on app/config/Countries.scala
> +    val hmrcName = alpha2ToHmrcName.getOrElse(isoCountry.alpha2, isoCountry.name)
alpha2ToHmrcName is a method and it's going to get called for every element in the country codes list

2021-12-10 12:46 UTC, burns238 commented on app/config/Countries.scala
> +    CountryInput(isoCountry.alpha3, hmrcName)
We could replace the use of this with IsoCountry which would make it reusable.

The CountryInput is basically the same but has the fields set to value and label or whatever, matching the terminology of the select list rather than a country.

2021-12-10 12:46 UTC, burns238 commented on app/config/Countries.scala
> +  private def alpha2ToHmrcName: Map[String, String] =
Make this a val?

2021-12-10 12:46 UTC, burns238 commented on app/config/Countries.scala
> +  private def iso3166CountryCodes: Seq[ISOCountry] =
We could make this a val as well, though it matters less as we're currently only calling it once below in countries.

2021-12-10 12:46 UTC, burns238 commented on app/config/Countries.scala
> +      .resourceAsStream("ISO_3166-alpha3-alpha2-numeric.json")
Could we move this and the file at the top to constants as we're reusing them in the exceptions

2021-12-10 13:12 UTC, liampan commented on app/config/Countries.scala
> +  private def alpha2ToHmrcName: Map[String, String] =
hmm agree with the above comment about it getting called multiple times, so will have a rejiggle. I made these defs as they only get called once on creation of the class it would be nice to save them from memory

2021-12-10 13:12 UTC, liampan commented on app/config/Countries.scala
> +      .resourceAsStream("ISO_3166-alpha3-alpha2-numeric.json")
can do :)

2021-12-10 13:13 UTC, liampan commented on app/config/Countries.scala
> +    CountryInput(isoCountry.alpha3, hmrcName)
I quite liked the CountryInput object as an interface for the relevance of this iso stuff to the application

2021-12-10 13:13 UTC, liampan commented on app/config/Countries.scala
> +    CountryInput(isoCountry.alpha3, hmrcName)
i guess we could add defs to the isoCountry object for value and label to provide this 🤔

2021-12-10 13:15 UTC, burns238 commented on app/config/Countries.scala
> +  private def alpha2ToHmrcName: Map[String, String] =
Call it once at the start of the countries val then?

2021-12-10 13:16 UTC, burns238 commented on app/config/Countries.scala
> +    CountryInput(isoCountry.alpha3, hmrcName)
I think it makes more sense to store them as countries, and we then decide what a label is and what a value is at the point where we create the select list. I think it makes it more understandable throughout the application, and more reusable so we can use it to get the name from a char 3 i nthe views etc

2021-12-13 12:06 UTC, burns238 approved these changes

2021-12-13 12:07 UTC, burns238 approved these changes

2021-12-13 15:41 UTC, merged