HOSS2-325-Update Passport Search Not Found content
hmrc/home-office-immigration-status-frontend pull request #116
Opened 2021-12-14 11:11 UTC by AdamCoops

2021-12-14 11:23 UTC, burns238 requested changes

2021-12-14 11:23 UTC, burns238 commented on app/views/components/ShowChangeQuery.scala.html
> +            Row("nino", "generic.nino", q.nino.nino, "", "nino", "generic.nino", query),
We've lost change-nino here.
Also if the span message key is the same as the text message key we don't have to pass it in here.

2021-12-14 11:23 UTC, burns238 commented on app/views/components/ShowChangeQuery.scala.html
> +            Row("idnumber", "lookup.mrz.label", q.documentNumber, "change-id-number", "documentNumber", "mrz.type", query),
Could we make the IDs here camel case?

2021-12-14 11:23 UTC, burns238 commented on app/viewmodels/RowWithActionViewModel.scala
> +    case f: MrzSearchFormModel  => s"${routes.SearchByMrzController.onPageLoad(false).url}#$fieldId"
`f` here can be a wildcard since we aren't using the actual object

2021-12-14 11:23 UTC, burns238 commented on test/views/components/ShowChangeQuerySpec.scala
> +    }*/
Do these need finishing?

2021-12-14 11:25 UTC, AdamCoops commented on test/views/components/ShowChangeQuerySpec.scala
> +    }*/
Yes

2021-12-14 11:25 UTC, AdamCoops commented on app/views/components/ShowChangeQuery.scala.html
> +            Row("idnumber", "lookup.mrz.label", q.documentNumber, "change-id-number", "documentNumber", "mrz.type", query),
Yes

2021-12-14 15:16 UTC, liampan approved these changes

2021-12-15 15:43 UTC, burns238 approved these changes

2021-12-15 16:04 UTC, merged