DDCE-2639 : Upgrade sbt + other libs and run scalafmt + scalastyle
hmrc/home-office-immigration-status-frontend pull request #186
Opened 2022-08-15 15:26 UTC by lmugnai

2022-08-16 13:36 UTC, frikit requested changes

2022-08-16 13:36 UTC, frikit commented on project/AppDependencies.scala
>    val jettyOverrides = Seq(
also every time we do updates we were trying to remove these overrides to have less things to maintain.

this was done for ```    "com.github.tomakehurst"  % "wiremock"                 % "2.27.2",```
if you try to upgrade to ```      "com.github.tomakehurst"        % "wiremock-jre8"            % "2.33.2",``` I think we are able to fix the overrides issue with wiremock server and then you can delete all overrides

I tried a small test it was complaining on ```    "com.fasterxml.jackson.module" %% "jackson-module-scala"     % "2.13.3"``` but once you add this seems to be working, anyway I am not able to do full round of test manual, AT... but its worth a try

2022-08-17 08:36 UTC, lmugnai commented on project/AppDependencies.scala
>    val jettyOverrides = Seq(
I think we are straying way off the scope of the ticket now. This was a simple sbt update which I don't think should turn into a big refactor. Let's create a new ticket for this.

2022-08-17 08:38 UTC, frikit commented on project/AppDependencies.scala
>    val jettyOverrides = Seq(
I am happy with we will create a new jira for this

2022-08-17 08:40 UTC, frikit approved these changes
LGTM!

2022-08-17 09:23 UTC, merged