DDCE-4358 : Fix a11y issues + remove beta banner
hmrc/home-office-immigration-status-frontend pull request #203
Opened 2023-07-26 13:18 UTC by lmugnai

2023-07-26 14:18 UTC, lmugnai commented
I've created this ticket to address the removal of SecureGCMCipher
https://jira.tools.tax.service.gov.uk/browse/DDCE-4534

2023-07-27 15:34 UTC, EdCope requested changes
The only addition is putting https://github.com/hmrc/bc-passengers-frontend#accessibility-tests instructions to the Readme

2023-07-28 09:16 UTC, EdCope reviewed
The only addition is putting https://github.com/hmrc/bc-passengers-frontend#accessibility-tests instructions to the Readme

2023-07-28 09:16 UTC, EdCope commented on app/views/govuk_wrapper.scala.html
> -    @govukPhaseBanner(PhaseBanner(
Please remove `govukPhaseBanner: GovukPhaseBanner` template argument as well as component
and related messages https://github.com/hmrc/home-office-immigration-status-frontend/blob/main/conf/messages#L1-L5

2023-07-28 09:16 UTC, EdCope commented on app/views/AccessibilityStatementPage.scala.html
Can we change [this](https://github.com/hmrc/home-office-immigration-status-frontend/pull/203/files#diff-3fd07b5b94198d897607ff65829b674743beded8373da8d035a03fbbcc461858L40) path  `<a href="/check-immigration-status">`

2023-07-28 09:50 UTC, lmugnai commented on app/views/AccessibilityStatementPage.scala.html
Is this just so it will work in pre-prod envs?

2023-07-28 09:52 UTC, lmugnai commented on app/views/AccessibilityStatementPage.scala.html
Also, what do you want the content of the link to be? currently: https://admin.tax.service.gov.uk/check-immigration-status

2023-07-28 09:55 UTC, EdCope commented on app/views/AccessibilityStatementPage.scala.html
Yes just for pre-prod, I think the content can probably stay the same though(?)

2023-07-28 10:00 UTC, Taiwo-AB commented on app/views/AccessibilityStatementPage.scala.html
Yh the content can be the same. As the route is part of the service, I feel we should be able it should work in all pre-prod envs.

2023-07-28 10:00 UTC, lmugnai commented on app/views/AccessibilityStatementPage.scala.html
hmmm, I don't like the idea of having the link different to the content. I'm not really sure it needs changing. If we ever need to click on this link in any sort of testing capacity we can simply change the domain manually. I don't think we have any tests checking this either.

2023-07-28 10:01 UTC, lmugnai commented on app/views/AccessibilityStatementPage.scala.html
the only other way we could address this is to have this url built from config. Which just seems a bit overkill.

2023-07-28 10:03 UTC, Taiwo-AB commented on app/views/AccessibilityStatementPage.scala.html
Maybe the wording needs changing in that regard. Not a fan of hardcording urls within a service that doesn't work in any pre-prod envs.

2023-07-28 10:06 UTC, Taiwo-AB commented on app/views/AccessibilityStatementPage.scala.html
Maybe we just need a content around the link that doesn't specify the prod url like for example [here](https://github.com/hmrc/pbik-frontend/blob/3d4e4fd45e4ad3fb79006ca383c3a6909eadbc58/conf/messages#L226)

2023-07-28 10:11 UTC, Taiwo-AB commented on app/views/AccessibilityStatementPage.scala.html
Just had a look at the text, I don't think we need `, available at <a href="https://admin.tax.service.gov.uk/check-immigration-status">https://admin.tax.service.gov.uk/check-immigration-status</a></p>` I think the link should be `Check Immigration Status service`. what do you think?

2023-07-28 10:12 UTC, lmugnai commented on app/views/AccessibilityStatementPage.scala.html
Yes, I feel that would be better. I'll pass this by @matthew-barker-hmrc in Jess' absence

2023-07-28 10:12 UTC, Taiwo-AB commented on app/views/AccessibilityStatementPage.scala.html
Thanks

2023-07-28 10:44 UTC, EdCope approved these changes

2023-07-28 10:44 UTC, merged