HOSS2-168-NotAva Refactor
hmrc/home-office-immigration-status-frontend pull request #30
Opened 2021-10-18 09:39 UTC by AdamCoops

2021-10-18 09:47 UTC, liampan commented on app/uk/gov/hmrc/homeofficeimmigrationstatus/views/StatusNotAvailablePageContext.scala
> +    ).flatten
As these are all Some, we can loose them and drop the flatten, saving the compiler a job :)

2021-10-18 09:47 UTC, liampan commented on app/uk/gov/hmrc/homeofficeimmigrationstatus/views/error_template.scala.html
> +            <a href="@hd" rel="noopener noreferrer" class="govuk-link" target="_blank"> @messages("status-check-failure.contact-helpdesk-link")</a>
nice spot :+1:

2021-10-18 09:49 UTC, liampan commented on app/uk/gov/hmrc/homeofficeimmigrationstatus/views/StatusNotAvailablePage.scala.html
>  @(context: StatusNotAvailablePageContext)(implicit request: Request[_], messages: Messages, appConfig: AppConfig)
I can't add a comment there, but i think `@locale` can be removed now :)

2021-10-18 09:50 UTC, liampan commented on app/uk/gov/hmrc/homeofficeimmigrationstatus/views/StatusNotAvailablePage.scala.html
> +@import uk.gov.hmrc.homeofficeimmigrationstatus.views.{DateFormat, ISO31661Alpha3, StatusNotAvailablePageContext}
why is this imported?

2021-10-18 12:14 UTC, liampan requested changes

2021-10-18 12:14 UTC, liampan commented on it/uk/gov/hmrc/homeofficeimmigrationstatus/controllers/HomeOfficeImmigrationStatusFrontendControllerISpec.scala
> -        checkHtmlResultWithBodyText(result, "31 January 2001")
This test should still be passing. I think we need a spec for the view, The formatting for DOB is wrong

2021-10-18 13:44 UTC, AdamCoops commented on it/uk/gov/hmrc/homeofficeimmigrationstatus/controllers/HomeOfficeImmigrationStatusFrontendControllerISpec.scala
> -        checkHtmlResultWithBodyText(result, "31 January 2001")
Yeah, so this test is broke and causes the failure. As to why or how, not sure yet. the DOB format exists in two forms in that view-spec, and all of those pass so unless we change how we display the date? or the data has changed for this test maybe.

2021-10-19 13:31 UTC, liampan commented on test/uk/gov/hmrc/homeofficeimmigrationstatus/views/StatusNotAvailableViewSpec.scala
> +  }
just need a test for the summary list to be rendered

```suggestion
     "have the summary list" in {
         assertRenderedById("notAvailablePersonalData")
     }
  }
```

2021-10-19 13:31 UTC, liampan commented on app/uk/gov/hmrc/homeofficeimmigrationstatus/views/StatusNotAvailablePageContext.scala
> +  def notAvailablePersonalData(implicit messages: Messages) =
a test will needed added to the contextSpec for the construction of this Sequence

2021-10-19 13:31 UTC, liampan commented on test/uk/gov/hmrc/homeofficeimmigrationstatus/views/StatusNotAvailableViewSpec.scala
> +  }
and a test to assert the button is present can use a verify for this as you've mocked it if you use the searchAgainButton Component

2021-10-26 12:55 UTC, merged