HOSS2-78-Update search comp
hmrc/home-office-immigration-status-frontend pull request #74
Opened 2021-11-22 13:14 UTC by AdamCoops

2021-11-22 13:21 UTC, burns238 requested changes

2021-11-22 13:21 UTC, burns238 commented on app/views/components/identityDocumentType.scala.html
> +   <option value="published" selected>@messages("lookup.passport")</option>
Have the left the example values in?

2021-11-22 13:21 UTC, burns238 commented on app/views/components/identityDocumentType.scala.html
> +  <select class="govuk-select" id="sort" name="sort">
We probably want to use the component that we have available from the plat frontend hmrc lib:

https://github.com/hmrc/play-frontend-hmrc/blob/main/src/main/twirl/uk/gov/hmrc/govukfrontend/views/components/GovukSelect.scala.html

We then just need to pass that this case class:
https://github.com/hmrc/play-frontend-hmrc/blob/main/src/main/scala/uk/gov/hmrc/govukfrontend/views/viewmodels/select/Select.scala

2021-11-22 13:23 UTC, AdamCoops commented on app/views/components/identityDocumentType.scala.html
> +   <option value="published" selected>@messages("lookup.passport")</option>
Whoops

2021-11-24 09:09 UTC, burns238 approved these changes

2021-11-24 14:54 UTC, merged