HOSS2-338-Update Multiple matches text to be dynamic
hmrc/home-office-immigration-status-frontend pull request #96
Opened 2021-12-01 14:52 UTC by AdamCoops

2021-12-03 10:56 UTC, liampan commented on app/views/MultipleMatchesFoundPage.scala.html
> +    alternateSearch: components.AlternateSearchLink,
dont think this component is being used in here anymore

2021-12-03 10:56 UTC, liampan commented on app/views/MultipleMatchesFoundPage.scala.html
> +    <p id="show-query"> @showChangeQuery(query)</p>
whats the reasoning behind this? 
The components themselves should handle their own id's.
Not sure this adds anything

2021-12-03 10:56 UTC, liampan commented on app/views/components/AlternateLinkText.scala.html
> +@if(!IsNinoSearch) { <p class="govuk-body" id="ninolink"> @messages("status-check-failure-conflict")  @alternateSearch(
can we simplify this to an if/else expression

2021-12-03 10:56 UTC, liampan commented on test/views/GovukWrapperViewSpec.scala
>    lazy val sut = inject[MultipleMatchesFoundPage]
bizarre this spec uses this file to test this, we can refactor if you want lmk

2021-12-03 10:56 UTC, liampan commented on conf/messages
> +status-check-failure-conflict='You can change the customer's details you have entered or '
will need to use the dodgey looking apostrophe for in the midde of messages, there are others in this file somewhere you can c&p

2021-12-03 10:56 UTC, liampan commented on conf/messages
> +status-check-failure-conflict='You can change the customer's details you have entered or '
found it
```suggestion
status-check-failure-conflict='You can change the customer’s details you have entered or '
```

2021-12-03 10:56 UTC, liampan commented on test/views/MultipleMatchesFoundViewSpec.scala
> +      //when(mockAppConfig.documentSearchFeatureEnabled).thenReturn(false)
think we need this, it will need to be used like the test above to take affect. Can only assume its returning null and scala is turning that to a false bool 🤔

2021-12-03 10:56 UTC, liampan commented on test/views/MultipleMatchesFoundViewSpec.scala
> +      assertRenderedById(doc, "show-query")
this asserts the p tag is there but not actually the element is being used.

2021-12-03 10:56 UTC, liampan commented on app/controllers/StatusResultController.scala
> +      case StatusCheckConflict(_) => Ok(multipleMatchesFoundPage(query, query.isInstanceOf[NinoSearchFormModel]))
we could move this logic in to the view, as it already has a query passed in, it could work this out

2021-12-03 12:18 UTC, AdamCoops commented on app/views/MultipleMatchesFoundPage.scala.html
> +    <p id="show-query"> @showChangeQuery(query)</p>
It makes the tests work.

2021-12-07 12:48 UTC, burns238 requested changes

2021-12-07 12:48 UTC, burns238 commented on app/views/MultipleMatchesFoundPage.scala.html
> +    <p id ="search-button"> @searchAgainButton()</p>
Why are we wrapping these in a P tag?

If this is for the tests for the former we should be checking for the existence of a `inputted-data` ID instead of show-query, because that's the ID that we're passing in in the component.

For the second there doesn't seem to be a way to pass an ID to the button component, but do we need one? We could in the tests check for an element with class govuk-button and then check that the href attribute was correct rather than wrapping these like this?

2021-12-07 12:48 UTC, burns238 commented on test/views/MultipleMatchesFoundViewSpec.scala
> +      assertRenderedById(doc, "show-query")
This is what I mean above - the tests don't test for the existence of the button or the change section, just that those P tags exist

2021-12-07 13:59 UTC, burns238 approved these changes

2021-12-07 14:00 UTC, merged